// Code generated by "stringer -type=SymbolKind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SkInvalid-0]
	_ = x[SkConst-1]
	_ = x[SkLet-2]
	_ = x[SkVar-3]
	_ = x[SkProcArg-4]
	_ = x[SkVarProcArg-5]
	_ = x[SkLoopIterator-6]
	_ = x[SkVarLoopIterator-7]
	_ = x[SkEnum-8]
}

const _SymbolKind_name = "SkInvalidSkConstSkLetSkVarSkProcArgSkVarProcArgSkLoopIteratorSkVarLoopIteratorSkEnum"

var _SymbolKind_index = [...]uint8{0, 9, 16, 21, 26, 35, 47, 61, 78, 84}

func (i SymbolKind) String() string {
	if i < 0 || i >= SymbolKind(len(_SymbolKind_index)-1) {
		return "SymbolKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SymbolKind_name[_SymbolKind_index[i]:_SymbolKind_index[i+1]]
}
