// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TkInvalid-0]
	_ = x[TkIdent-1]
	_ = x[TkQuotedIdent-2]
	_ = x[TkNewLine-3]
	_ = x[TkSemicolon-4]
	_ = x[TkComma-5]
	_ = x[TkOperator-6]
	_ = x[TkStrLit-7]
	_ = x[TkRawStrLit-8]
	_ = x[TkIntLit-9]
	_ = x[TkHexLit-10]
	_ = x[TkFloatLit-11]
	_ = x[TkNilLit-12]
	_ = x[TkDocComment-13]
	_ = x[TkVar-14]
	_ = x[TkLet-15]
	_ = x[TkConst-16]
	_ = x[TkOpenBrace-100]
	_ = x[TkCloseBrace-101]
	_ = x[TkOpenBracket-102]
	_ = x[TkCloseBracket-103]
	_ = x[TkOpenCurly-104]
	_ = x[TkCloseCurly-105]
	_ = x[TkEof-23]
	_ = x[TkCount-24]
}

const (
	_TokenKind_name_0 = "TkInvalidTkIdentTkQuotedIdentTkNewLineTkSemicolonTkCommaTkOperatorTkStrLitTkRawStrLitTkIntLitTkHexLitTkFloatLitTkNilLitTkDocCommentTkVarTkLetTkConst"
	_TokenKind_name_1 = "TkEofTkCount"
	_TokenKind_name_2 = "TkOpenBraceTkCloseBraceTkOpenBracketTkCloseBracketTkOpenCurlyTkCloseCurly"
)

var (
	_TokenKind_index_0 = [...]uint8{0, 9, 16, 29, 38, 49, 56, 66, 74, 85, 93, 101, 111, 119, 131, 136, 141, 148}
	_TokenKind_index_1 = [...]uint8{0, 5, 12}
	_TokenKind_index_2 = [...]uint8{0, 11, 23, 36, 50, 61, 73}
)

func (i TokenKind) String() string {
	switch {
	case 0 <= i && i <= 16:
		return _TokenKind_name_0[_TokenKind_index_0[i]:_TokenKind_index_0[i+1]]
	case 23 <= i && i <= 24:
		i -= 23
		return _TokenKind_name_1[_TokenKind_index_1[i]:_TokenKind_index_1[i+1]]
	case 100 <= i && i <= 105:
		i -= 100
		return _TokenKind_name_2[_TokenKind_index_2[i]:_TokenKind_index_2[i+1]]
	default:
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
